# Konekcija ka MariaDB bazi podataka
spring.datasource.url=jdbc:mariadb://localhost:3306/evoting_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate podešavanja
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# Pošto smo ručno napravili tabele, stavljamo 'validate' da Hibernate samo provjeri strukturu
spring.jpa.hibernate.ddl-auto=validate

# Prikazivanje SQL-a u konzoli (odlično za debugging tokom razvoja)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
